name: Backend Tests

on:
  push:
    branches: [ "main" ]

env:
  HOME: /home/aiku
  XDEBUG_MODE: coverage

jobs:
  laravel-tests:
    name: Run backend tests 🧪
    runs-on: [ cloud ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Npm install
        run: npm ci --ignore-scripts
      - name: Composer install
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Prepare environment
        run:  |
          ln -s ../../../../.pgpass .pgpass
          ln -s ../../../../env.aiku.testing .env.testing
          ln -s ../../../../env.aiku.testing .env
          mkdir private
          cd private
          ln -s ../../../../../artifacts/fa .
      - name: Generate database dumps 📚
        run: ./generate_testing_db_dumps.sh php8.3 aiku
      - name: build app
        run: npm run build
      - name: Run test
        run: vendor/bin/pest -d memory_limit=-1 --coverage-clover clover.xml --exclude-group=aurora-fetch
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          file: ./clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true