name: Backend Tests

on:
  push:
    branches: [ "main" ]

env:
  HOME: /home/devops

jobs:
  laravel-tests:
    name: Run backend tests 🧪
    runs-on: [ self-hosted, linux, x64, testing ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Npm install
        run: npm ci
      - name: Composer install
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Prepare environment
        run:  |
          ln -s ../../../../env.aiku.testing .env.testing
          ln -s ../../../../env.aiku.testing .env
      - name: Generate database dumps 📚
        run: ./generate_testing_db_dumps.sh ${{vars.TESTING_DB_PORT}}
      - name: Run test
        run: vendor/bin/pest
